# DeluxeMenus 1.14.0-Release main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/clips-plugins/deluxemenus


# Recuerda que este archivo tiene que ir en la carpeta de DeluxeMenus (example: /home/container/plugins/DeluxeMenus/)

debug: HIGHEST
check_updates: true
gui_menus:
  warps_menu:
    file: warps_menu.yml
